### ISSUE TITLE
[Bug]: Configurations cannot be created and consumed in fabric

### ISSUE THREAD

**Issue by baka4n** [Team-Resourceful/Resouceful-Config#12]
### Bug Description

![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/f31dcf81-f5e8-4df2-aeb3-22705bda246f)
some code
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/9c00afe4-e55d-4927-b1ce-d268115c99b6)
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/ba20ce64-d3ea-488e-8f64-1377bf052072)
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/d345bb7d-eaf5-41dd-8b3c-f8bfeb668a95)
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/c2cd6d0d-595c-4e93-bf47-c95e1b271c30)
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/c50e5d1b-c01a-4502-a59c-60ebc7f990ba)
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/a43790a2-53b0-418d-a2f5-50baaf4ffc91)

### Version

1.0.20

### Mod Loader Version

1.19.2-lastversion

### Mod Loader

Fabric

**Comment by ThatGravyBoat** [comment]
did you register your config?

**Comment by ThatGravyBoat** [comment]
nvm I am just blind, can you provide a source code instead of screenshots

**Comment by baka4n** [comment]
> nvm 我只是瞎了，你能提供源代码而不是屏幕截图吗

okey. this repo is on github : https://github.com/dove-home-team/rewrite-save-mod-dove-home-mod
This code resource is located in the dovehomemod directory

**Comment by baka4n** [comment]
Is it a problem caused by the architectury API structure? Forge can be used, fabric can't be created and used, I saw that the ad code is written in a similar way, but my style is like this

**Comment by ThatGravyBoat** [comment]
Can you check if the registerConfig method that you created is being called and see what the output of config is?

**Comment by baka4n** [comment]
It seems that two messages are printed in it without going through this, but it doesn't work, maybe it's a modmenu issue?

**Comment by baka4n** [comment]
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/27fe1be6-1372-48cf-8d3e-ac88159fc5cb)

**Comment by ThatGravyBoat** [comment]
what are the errors you have there, because some of them may be related to the config

**Comment by baka4n** [comment]
The console only prints and clicks on the modmenu to show that I don't have a logo, and then it doesn't print that I have other errors

**Comment by baka4n** [comment]
Are there any sample tutorials?

**Comment by baka4n** [comment]
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/6ed3b2a6-c57f-47a2-826b-821b9244c651)
Is there a problem with this link?

**Comment by baka4n** [comment]
Or when introducing dependencies, use modApi

**Comment by ThatGravyBoat** [comment]
the icon error is from fabric because you have something wrong in your fabric.mods.json but it shouldnt affect this, architectury does load stuff differently so make sure the config button isnt present on the `generated_xxxxxx` mod that is auto includes to work around mod loading issues in dev. I use architectury with this library exclusively so there shouldnt be any issues, you can take a look at this https://github.com/AlexNijjar/Extractinator it uses it as is pretty small so it should be easy to follow.

**Comment by baka4n** [comment]
Maybe I found the reason, it's because I'm confused, bakalib's fabric modid is written as dovehomemod, because I copied and changed the forge and didn't change the fabric, and it's more convenient to use variables later. I'm not too embarrassed to bother you for so long, hahahaha

**Comment by baka4n** [comment]
![image](https://github.com/Team-Resourceful/Resourceful-Config/assets/60695447/c7f5d496-0fc1-4383-afc7-57ce0af74e44)
ok thanks you
