### ISSUE TITLE
Resourceful Config makes Minecraft crash

### ISSUE THREAD

**Issue by IReallyPlay** [Team-Resourceful/Resouceful-Config#15]
### Bug Description

Hello, we recently created a modpack for Forge 1.19.2 and when we launch Minecraft I'm able to launch Minecraft with no problem but my friend couldn't launch Minecraft. There is no error code too it just says "Uncompatible graphics card" and closes. Also we are certain that error is caused by Resourceful Config 1020 (Forge).
Thanks

### Expected Behavior

Launch minecraft with no problem.

### Version

1.0.2.0

### Mod Loader Version

Forge 43.3.0 / 1.19.2

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Can you please provide your log files so I can see if it could be a mod incompatibility or some other issue?

**Comment by IReallyPlay** [comment]
Sure :) I'll send it in a few minutes

**Comment by IReallyPlay** [comment]
Hello, my friend is just back from his vacation and seams like i solved the
problem. Resourceful config was not working quite with Dynamic Trees mod.
