### ISSUE TITLE
[Bug]: game crahes a few seconds after entering to the loading screen

### ISSUE THREAD

**Issue by hjro1** [Team-Resourceful/Resouceful-Config#17]
### Bug Description

when i try to open the game it crashes when i have resourceful config, it only give me this message 
Minecraft. 
Error:
Exception in thread "main"

### Version

2.1.2

### Mod Loader Version

1.20.1-47.2.23

### Mod Loader

Forge

**Comment by ThatGravyBoat** [comment]
Full crash log is required

**Comment by hjro1** [comment]
> Full crash log is required

thats the crash log, however i discovered that the game dosent crash when i have the mod but when i add a mod that dependes of it (icarus and anvil fix in this case) it gives me the error, any idea why?

**Comment by ThatGravyBoat** [comment]
that is not a crash log, a crash log is located in the minecraft folder in the `crash-reports` folder you will find one with todays date and latest time of crash send that.

**Comment by hjro1** [comment]
> that is not a crash log, a crash log is located in the minecraft folder in the `crash-reports` folder you will find one with todays date and latest time of crash send that.

i checked the carpet, its not generating the crash log and instead it only give me that error, but anyway for what im seeing here its possible that this mod its not the problem so i will check if anybody reported this bug on the other mods that i mentioned earlier, have a nice day
