### ISSUE TITLE
Latest version is not tagged as 1.20.6 compatible in both Curseforge and Modrinth

### ISSUE THREAD

**Issue by costentz** [Team-Resourceful/Resouceful-Config#19]
### Bug Description

This means that mods on 1.20.6 that depend on it won't make modded launchers automatically download it, and the game will crash at startup.

### Version

2.5.1

### Mod Loader Version

1.20.6 - 0.15.11

**Comment by costantino2000** [comment]
I see that this was closed as completed, but on Curseforge it still says 1.20.5 only.
