### ISSUE TITLE
[Bug]: Crash on startup with NeoForge 21.0.86

### ISSUE THREAD

**Issue by NielsPilgaard** [Team-Resourceful/Resouceful-Config#22]
### Bug Description

I crash on startup when I have NeoForge 21.0.86 and Resourceful Config in the same instance.

### Expected Behavior

For the game to load

### Version

resourcefulconfig-neoforge-1.21-3.0.2

### Mod Loader Version

21.0.86

### Mod Loader

N/A

### Logs or additional context

https://gist.github.com/NielsPilgaard/45f915b28642f7115a1f713f1abdce12

**Comment by ThatGravyBoat** [comment]
This seems to be an extremesoundmuffler issue not Resourceful Config

**Comment by NielsPilgaard** [comment]
Oh, sorry about that!
