### ISSUE TITLE
Json5 instead of normal json

### ISSUE THREAD

**Issue by HttpRafa** [Team-Resourceful/Resouceful-Config#5]
I have a suggestion. Why don't you use Json5 which supports comments and other things?

**Comment by ThatGravyBoat** [comment]
This would require an external library or a custom implementation, but I think I could add support for proper comments by following the JSONC spec which is just the Json spec with comments. 

Will keep this in mind.

**Comment by HttpRafa** [comment]
Ok 👍

**Comment by ThatGravyBoat** [comment]
Added in 1.1.3
