### ISSUE TITLE
[Suggestion] Add the mod on Modrinth

### ISSUE THREAD

**Issue by Heus-Sueh** [Team-Resourceful/Resouceful-Config#9]
### Is your feature request related to a problem?

unfortunately the mod does not appear to download directly from Prism Launcher

### Solution(s)

.

### Describe alternatives you've considered

.

### Mod Version

.

### Mod Loader Version

.

### Mod Loader

Fabric

**Comment by Epic428** [comment]
It is? https://modrinth.com/mod/resourceful-config

**Comment by Epic428** [comment]
If it isn’t downloading on the prism launcher then that is an issue with the launcher or the api it is using to download the mod

**Comment by Heus-Sueh** [comment]
my mistake, it was in modrinth, mine had a filter for 1.20.1 that's why I wasn't finding it, sorry.

**Comment by p3lim** [comment]
had the same issue, the 2.0.0 version on modrinth isn't flagged for 1.20.1, while it is on curseforge.

expanding the launcher filter solved it temporarily.
